# Generated by Django 4.0.2 on 2022-02-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_anwserimage_questionimage_question_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnwserImage',
            new_name='AnswerImage',
        ),
    ]
