# Generated by Django 4.0.2 on 2022-02-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_anwserimage_answerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='res_by',
        ),
        migrations.DeleteModel(
            name='AnswerImage',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='question',
            name='images',
        ),
        migrations.RemoveField(
            model_name='question',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionImage',
        ),
    ]
