# Generated by Django 4.0.2 on 2022-02-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_question_questionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionimage',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.ManyToManyField(to='blogs.QuestionImage'),
        ),
    ]
