# Generated by Django 4.0.2 on 2022-02-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_questionimage_question_question_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='images',
        ),
        migrations.DeleteModel(
            name='QuestionImage',
        ),
    ]
