# Generated by Django 4.0.2 on 2022-02-08 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_remove_question_images_delete_questionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_image/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.question')),
            ],
        ),
    ]
