# Generated by Django 4.0.2 on 2022-02-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerImage',
        ),
    ]
