# Generated by Django 4.0.2 on 2022-02-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_delete_answerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='answer_image/')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.answer')),
            ],
        ),
    ]
