# Generated by Django 4.0.2 on 2022-02-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_payment_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='basket',
        ),
        migrations.AddField(
            model_name='payment',
            name='basket',
            field=models.ManyToManyField(to='Order.Basket'),
        ),
    ]
